### ISSUE TITLE
Deleting a cookie is awkward

### ISSUE THREAD

**Issue by jakearchibald** [WICG/cookie-store#12]
This may depend on https://github.com/bsittler/async-cookies-api/issues/11

When I get cookies via `getAll`, it feels like I should just be able to pass them to `delete` rather than having to split the object up into multiple arguments.

**Comment by bsittler** [comment]
I think write operations for multiple cookies aren't quite atomic today,
since they come from distinct Set-Cookie: headers/document.cookie
writes/meta tags each processed separately, although read operations for
multiple cookies are (or at least should be), since they come from a single
Cookie: header/document.cookie read and _should_ reflect a coherent
serialization.

**Comment by jakearchibald** [comment]
I don't think I explained well in the OP.

I'm saying:

```js
navigator.cookies.getAll().then(cookies => {
  navigator.cookies.delete(cookies[0]);
})
```

…should work, rather than having to split them out into other arguments. Although this may be another side-effect of this being un-map-like.

**Comment by bsittler** [comment]
I see. This would require knowing the path+domain for each returned cookie

**Comment by jakearchibald** [comment]
Yeah, very much linked to https://github.com/bsittler/async-cookies-api/issues/11

**Comment by bsittler** [comment]
Note that Origin-Cookie (if/when that becomes real) makes all those problems disappear. However it's also not backward compatible and may even call for a separate JS API for reads, just as the draft RFC specifies a separate request header today although it shares the same header for setting cookies

**Comment by bsittler** [comment]
FYI this issue is still present in the more recent API now outlined in [the explainer](explainer.md) but I think that with sane defaults (mostly path=/ by default and omitted domain by default for write/delete operations, along with recommending __Host- and __Secure- and enforcing their properties in writes through this API) we can make progress toward cleaning up this mess.

**Comment by inexorabletash** [comment]
explainer link is bad (needs a `../` path segment)

**Comment by bsittler** [comment]
Fixed, thanks!

**Comment by bsittler** [comment]
Hah! Apparently the content preview doesn't use base href

**Comment by pwnall** [comment]
@jakearchibald I've updated the explainer to reflect the current Chrome implementation plus planned additions. I plan to export cookie metadata in such a way that the use case you describe (pass `get` / `getAll` result to `delete`) works.

Thank you very much for your feedback here!
