### ISSUE TITLE
CookieChangeEvent cannot have CookieList attributes

### ISSUE THREAD

**Issue by domenic** [WICG/cookie-store#156]
CookieList is defined as a `sequence<CookieListItem>`.

However, [attributes cannot be of sequence type](https://heycam.github.io/webidl/#idl-attributes).

I think these should instead be `FrozenArray<CookieListItem>`.

Additionally, it would be good to add web platform tests that `event.changed === event.changed`, and `event.deleted === event.deleted`. (This is a common failure mode for array-valued IDL attributes.)

**Comment by ayuishii** [comment]
Thanks for catching this!

Instead of updating CookieList to use `FrozenArray`, I updated CookieChangeEvent to use `FrozenArray<CookieListItem>` so the other instances can continue using `sequence<CookieListItem>`. Some discussion on this can be found on the [PR](https://github.com/WICG/cookie-store/pull/173#discussion_r485906412), but let me know if that sounds ok. 

Will track implementation changes in Chrome [here](https://crbug.com/1124841).

**Comment by domenic** [comment]
The spec looks good now! I might remove the indirection of the `CookieList` typedef, personally, but that's a style choice. Happy to close this.
