### ISSUE TITLE
Explainer: cookies != storage

### ISSUE THREAD

**Issue by bsittler** [WICG/cookie-store#30]
Developers may be tempted to use cookies as a key/value store for their applications. The explainer should describe the limitations of such an approach and refer developers to other storage APIs for situations where cookies are inappropriate or suboptimal, perhaps with short code samples to ease the transition

**Comment by jokeyrhyme** [comment]
I'd also like to see this in the reverse: reasons why we should still use Cookies instead of IndexedDB, etc which are already available to Service Workers.

I don't deny that cookies have their uses, especially in JavaScript-free areas, but is there still a compelling reason to have an improved Cookies API anywhere we have JavaScript?

Also, any browser implementing this new and improved Cookies API will likely have already implemented IndexedDB, etc. And this new API will need documented compelling reasons to encourage cross-browser implementation.

I don't mean to sound antagonistic. I'm genuinely interested in seeing further exploration of the ideas in this proposal.

**Comment by annevk** [comment]
Cookies cross the origin boundery and identify the user earlier than any other form of storage. That is why folks want them in workers.

**Comment by bsittler** [comment]
Excellent points! I will add: cookies can be used as an ambient authentication factor and for preference storag, and for both same-origin and cross-origin requests - and even, in some cases, for requests from outside the top-level page's registered domain entirely. They are, for example, used this way in mash-ups, portals, feeds, and other multiple-tenant-in-one-page web applications to permit embedded content to render according to the viewer's preferences and authenticated access without requiring that the top-level site reverse-proxy all the content and also without requiring that all the content serving from parties other than the owner of the top-level site be implemented in scripts (either service workers with foreign fetch or service IFRAMEs)

**Comment by pwnall** [comment]
I'd much rather stick to stating that this API is for interacting with HTTP cookies. Cookies are fairly magical, in that they get included in HTTP requests based on a complex set of rules, so I can't think of an use case where I'd actively recommend them.

It seems to me that cookies are used for their scope (the only client-side storage that transcends same-origin policy) or for integration with a backend. So, folks who use cookies already know they need them, and I don't think we'd want to encourage anyone else.

I'll close this issue because I don't plan to add any encouragement / discouragement to the explainer. Please don't let this discourage you from submitting the text you'd like to see as a PR!
