### ISSUE TITLE
Methods should have optional CookieStore{Get,Set}Options?

### ISSUE THREAD

**Issue by rtoy** [WICG/cookie-store#49]
The dictionaries `CookeStoreGetOptions` and `CookeStoreSetOptions` don't have any required members.  This implies that the options parameters for the methods that have these parameters must be marked optional.

(Bikeshed produces a fatal error for this.)

**Comment by inexorabletash** [comment]
Nice find!

To match the semantics of the API, I think we need to either mark the arguments optional and enforce the requirement in prose, or make additional dictionaries. The cases in question are:

* `set(options)` - name option is required
* `delete(options)` - name option is required

* `set(name, value, options)` - name option would be an error
* `delete(name, options)` - name option would be an error

I think `CookieStoreGetOptions` is always optional in the IDL already, and semantically allowed to be absent in all cases (although both positional name and option name should be a typeerror?)

**Comment by bsittler** [comment]
At least initially I was assuming name is *not* required in any case, because there are actually no-name/empty-name cookies, and those should be reachable/deletable through this API if it is to be a drop-in async replacement for document.cookie. Omitted name would be equivalent to name: ''. I agree, though, that two different flavors of options make sense for the exploded/unexploded argument list forms of set/delete, one with (optional) name field and the other without any name field.

Also, the options parameter itself should always be optional. When omitted, e.g. in zero-argument delete(), it defaults to equivalent behavior to {name: '', path: '/', secure: true} [in https: context]; in zero-argument set(), it defaults to equivalent behavior to {name: '', value: '', path: '/', secure: true} [again, in https: context]. In the corresponding exploded versions, the defaults should instead be {path: '/', secure: true} for both [again, assuming https:].

**Comment by pwnall** [comment]
I think that skipping the name makes sense for `getAll`, where the default can be `name: '', matchType: 'startsWith'`. I don't see any merits in having an optional name in `get`, asides from consistency with `getAll`, but I consider that the consistency is a pretty good merit.

I think `set` and `delete` should require names. The default of `name: ''` is surprising to me, and I think that a promise rejection would be significantly more helpful (on average) than an empty name default. 


While writing the tests for this API, I found it odd that we support `set(name, {other options})` and `set({name: '...', other options})`. I think that get / getAll / delete should support a single argument that can be an option bag or a string, which would be a shorthand for `{name: string}`. Similarly, set should either support an options bag or name / value string arguments.

This would give us something along these lines

```webidl
interface CookieStore {
  Promise<CookieList> getAll(USVString name);
  Promise<CookieList> getAll(optional CookieStoreGetOptions options);
  Promise<CookieListItem?> get(USVString name);
  Promise<CookieListItem?> get(optional CookieStoreGetOptions options);

  Promise<void> set(USVString name, USVString value);
  Promise<void> set(CookieStoreSetOptions options);

  Promise<void> delete(USVString name);  
  Promise<void> delete(CookieStoreSetOptions options);
};
```

@inexorabletash WDYT?

**Comment by inexorabletash** [comment]
While that makes sense in the abstract, I think developers will expect to "upgrade" a call by adding an options dict, and not have to pull other arguments into the dict. i.e. `set(name, value)` upgrades to `set(name, value, options)`. 

I think that's specific to `set`, though. Your proposed `get`/`getAll`/`delete` seem intuitive. Is it okay if `set` deviates?

**Comment by pwnall** [comment]
If I understand correctly, this would be:

```
interface CookieStore {
  Promise<CookieList> getAll(USVString name);
  Promise<CookieList> getAll(optional CookieStoreGetOptions options);
  Promise<CookieListItem?> get(USVString name);
  Promise<CookieListItem?> get(optional CookieStoreGetOptions options);

  Promise<void> set(USVString name, USVString value, optional CookieStoreSetExtendedOptions options);
  Promise<void> set(CookieStoreSetOptions options);

  Promise<void> delete(USVString name);  
  Promise<void> delete(CookieStoreSetOptions options);
};
```

where `CookieStoreSetExtendedOptions` is `CookieStoreSetOptions` minus `name` and `value`?

**Comment by inexorabletash** [comment]
test updates pending
