### ISSUE TITLE
Formal spec should use TypeError or "SyntaxError" DOMException, not Error

### ISSUE THREAD

**Issue by domenic** [WICG/cookie-store#5]
Error is reserved for user-defined APIs, not web APIs.

Choosing between TypeError and "SyntaxError" DOMException is always a bit tricky. I think I'd lean toward "SyntaxError" in this case but @annevk might disagree.

**Comment by annevk** [comment]
I guess the question is whether this API can be made generic enough to be reusable by JavaScript hosts other than platform, e.g., node.js.

**Comment by bsittler** [comment]
@annevk for node.js would this be some sort of helper to construct response headers/parse request headers in the context of HTTP serving? An interface to a UA's cookie jar for cases where the node.js application is an HTTP client? Both? Something else entirely?

**Comment by annevk** [comment]
Those kind of scenarios, yes. I don't have any concrete ideas. Generally it makes sense to me that if you don't need to depend on platform concepts, you stick to the bits that are in ECMAScript already for ease of reuse later on.

**Comment by bsittler** [comment]
SyntaxError everywhere now

**Comment by annevk** [comment]
DOMException after all, then?

**Comment by bsittler** [comment]
Yes. I think it makes more sense to focus on browsers first since they have a fairly different view of cookies from severs, and some of the API's concepts (monitoring, script-visible subsets, async-cookies-api everything, etc.) don't seem to make much sense in the current Node processing model. If there is in fact a place for such an API in non-browser contexts I'd be happy to discuss it, though, ideally in a separate issue focused on the non-browser platform(s) and how the API would benefit them

**Comment by annevk** [comment]
That's not really a reason not to use TypeError though...

**Comment by bsittler** [comment]
Agreed! I went with SyntaxError because the errors being reported are all (or at least mostly) violations of cookie syntax rules.

**Comment by bsittler** [comment]
@domenic can you explain why you lean toward SyntaxError in this case? @pwnall started the implementation using TypeError and I guess we need to decide for real before it's too late :)

**Comment by domenic** [comment]
As you said, it's a violation of the syntax of a specific string. It doesn't matter much though unless you expect developers to be catching these errors and switching on them.

**Comment by pwnall** [comment]
FWIW, exception types are really easy to change in the current implementation, so I won't be upset if @domenic presents a good argument for SyntaxError. 

The one thing that I would like to ask for is that we throw the same exception everywhere, based on prior experience. The algorithms in IndexedDB throw different exception types in different steps, and covering that area of the spec (1) required a lot of tedious tests and (2) was a source of interop issues between us (Chrome) and Firefox. The issues have been solved, but that required engineering effort.

I used TypeError in the implementation because so far the errors that I covered were along the lines of "the options object has the wrong properties" (example: the cookie name passed both as a positional argument and as an exception). In fact, [the Blink code](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/cookie_store/CookieStore.cpp?q=exception_state.Throw) is fairly readable (if I dare say so myself) and it'll give you a better idea of what I mean.

I suppose I find SyntaxError a bit odd because the API is far enough removed from the (Set-)Cookie: header strings that all the errors I can see are type errors.

**Comment by pwnall** [comment]
I think it's safe to close this, as the Chrome implementation uses TypeError everywhere, and it's unlikely that we'd accidentally move away from that in the spec. Please reopen if you disagree.

Thank you very much for the great discussion here, everyone!
