### ISSUE TITLE
Is CookieListItem a valid parameter to delete?

### ISSUE THREAD

**Issue by dfabulich** [WICG/cookie-store#60]
`cookieStore.delete(options)` accepts `CookieStoreSetOptions`. It occurs to me that some folks might like to use the `CookieListItem` result of `cookieStore.getAll()` and pass it directly to `delete`, e.g.:

```js
cookieStore.getAll().then(cookies => Promise.all(map(cookie => cookieStore.delete(cookie))));
```

Perhaps [`deleteAll`](https://github.com/WICG/cookie-store/issues/58) would satisfy that use case, but maybe I'd want to write an arbitrary filter selecting cookies to delete:

```js
cookieStore.getAll().then(
  cookies => Promise.all(
    cookies.filter(cookie => cookie.name.length > 6)
    .map(cookie => cookieStore.delete(cookie))
  )
);
```

It seems like code like this _could_ work. `CookieListItem` (the result of `getAll`) has a subset of the properties of `CookieStoreSetOptions`. Will it work? Should it work?

**Comment by inexorabletash** [comment]
Re: `.map(cookie => cookieStore.delete)` 

Wouldn't that need to be:

`.map(cookieStore.delete.bind(cookieStore))`
or
`.map(cookie => cookieStore.delete(cookie))` 

... but that's a good point... since `CookieListItem` is a subset of `CookieStoreSetOptions` it "should" work. If not, that'd be surprising. We may want to have a test for this so as the API evolves we don't accidentally break it. For example, I can see us adding a `CookieStoreDeleteOptions` dict since we don't need `expires`. Including that shouldn't hurt since extra dict options are ignored, but what if we added one that changed semantics?

**Comment by dfabulich** [comment]
I definitely like the idea of adding a test for this.

(I've edited the initial sample to invoke the method from the correct context.)

**Comment by pwnall** [comment]
Per #12 we definitely want to be able to pass the result from `get` or `getAll` into `set` and `delete`. I hope to add proper tests for this in the nearby future.

@dfabulich I'd be happy to review a PR adding these tests, if you're interested and have time. Thank you!

**Comment by inexorabletash** [comment]
@dfabulich - I'd like to list you in the spec's acknowledgement section since you've given valuable feedback. What name should I use?
