### ISSUE TITLE
Describe CookieListItem attributes

### ISSUE THREAD

**Issue by bakulf** [WICG/cookie-store#80]
The spec doesn't say anything about when/how CookieListItem attributes are set.
Following WPTs I have questions:
1. why domain is often null? A Cookie should always have a valid domain.
2. why value is null when the cookie is deleted?
All must be well defined.

**Comment by inexorabletash** [comment]
Yep, the spec is a rough placeholder at the moment. Keep these coming, though!

Partially addressed in https://github.com/WICG/cookie-store/pull/79

**Comment by inexorabletash** [comment]
And re: domain - I believe it should always be defined as far as the storage model goes, but can be optional in the API as the default is provided by the origin of the global. This is analogous to the request-uri and domain attribute in the RFC.

**Comment by inexorabletash** [comment]
Also (and this should be in the spec) CookieListItem should always be fully populated when returned, but may be sparsely populated when the CookieChangeEvent is created from script (this also needs to be defined)

**Comment by inexorabletash** [comment]
Event type construction is defined in https://dom.spec.whatwg.org/#concept-event-create and doesn't need further specification, e.g. it references https://dom.spec.whatwg.org/#inner-event-creation-steps which handles initializing the `created` and `deleted` members from the init dict.

**Comment by inexorabletash** [comment]
I believe this should be resolved now. 

> The spec doesn't say anything about when/how CookieListItem attributes are set.

This is now specified. See https://wicg.github.io/cookie-store/#create-a-cookielistitem which is referenced in a few places.

> why domain is often null? A Cookie should always have a valid domain.

Input: https://wicg.github.io/cookie-store/#set-a-cookie - may be null on input from script (e.g. a `set()` or `delete()` call). Turns into a `Domain=xxx` input to RFC6265's algorithm.

Output: again, see https://wicg.github.io/cookie-store/#create-a-cookielistitem - the cookie's inherent `domain` property becomes part of the `CookieListItem`. Since cookies always have a `domain` this will always be populated.

> why value is null when the cookie is deleted?

Input: https://wicg.github.io/cookie-store/#delete-cookie-algorithm - we set it to the empty string as input to the RFC.

Output: https://wicg.github.io/cookie-store/#fire-a-change-event - the value is set to undefined in the event's dict.
