### ISSUE TITLE
What does cookieStore.get() return, and is it useful?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/cookie-store#94]
```js
const val = await cookieStore.get();
```

What is `val`? Does it make sense for args to `get` to be entirely optional?

**Comment by inexorabletash** [comment]
Aside: The [query cookies](https://wicg.github.io/cookie-store/#query-cookies) steps say that _name_ is optional, but then use it in a match. If that's supposed to treat unspecified _name_ as empty string, it should be explicit, otherwise it should be handled in [match](https://wicg.github.io/cookie-store/#matches).

**Comment by inexorabletash** [comment]
I believe the intent is that if _name_ is not specified then **query cookies** should not filter by name, which would be needed for `getAll()` to make sense.

Per current algorithms, `get()` (no arguments) would return the first cookie in scope (which agreed is not particular intuitive). I think we were waiting for feedback that this was confusing (such at this issue...)

**Comment by domenic** [comment]
Should we change this to reject now? I know there were some recent changes around argument behavior. Since there is no single required member of the dictionary, we can't make the argument required, but we could add prose which rejects the promise if no dictionary members are present. (See also https://github.com/heycam/webidl/issues/903.)

**Comment by ayuishii** [comment]
Rejecting the promise if no dictionary members are present sounds good to me. 
Created a ticket [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1124073) to track implementation in Chrome.

**Comment by ayuishii** [comment]
Closing since the spec has been updated, will continue to track Chrome implementation progress on [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1124073).
